wsdl: 'https://test.placetopay.com/soap/pse/?wsdl'
auth:
  login: '6dd490faf9cb87a9862245da41170ff2'
  tranKey: '024h1IlD'
  additional:
    - [name:'foo', value:'bar']
    - [name:'foo', value:'bar']